import Head from 'next/head'
import Link from 'next/link'
import Chip from '@mui/material/Chip';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.PUBLIC_PRE_FIX_PATH}/favicon.ico`} />
        <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <Link href="/kr">KR</Link> / <Link href={'/eng'}>ENG</Link>
        <Chip label="Chip Filled" />
        <Chip label="Chip Outlined" variant="outlined" />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
